spring:
  application:
    name: lovable-clone
    description: this is application

  datasource:
#    url: jdbc:postgresql://localhost:9000/testDB?sslmode=disable
#    username: testUser
    url: jdbc:postgresql://localhost:9010/pgvector-test
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  data:
    redis:
      host: localhost
      port: 6379

  ai:
    openai:
      api-key: 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
      base-url: https://openrouter.ai/api
      chat:
        options:
#          model: openai/gpt-5.2-codex
          model: stepfun/step-3.5-flash:free
#          model: qwen/qwen3-coder:free
#          model: nvidia/nemotron-3-super-120b-a12b:free
          temperature: 0.0

#  ai:
#    google:
#      genai:
#        api-key: AIzaSyBbbqyYWBCT0Q79jXK3_Bh_w4MQATQ1KEQ
#        model: gemini-pro

jwt:
  secret-key: as9b7aodlbjfkluosfd789ujeklfnlsduf90b8ha908w74tuqijvlckajdl

stripe:
  api:
    secret: sk_test_51T7eYXDUATaQjWRNPh0NV8ElYx4Ai5sLIVWD1tADBeqgOJh7zMdj7OUqRXsIgaM7kf1yOVLeccnHmehHFuw6ePeS00vz2TGpcf
  webhook:
    secret: whsec_30367c20879296c296f5936cd52b1a0e01bba945ddf4b727dad38881932eb50a

client.url: http://localhost:8080

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG

minio:
  url: http://localhost:9000          # or minio:9000 if inside docker network
  access-key: minioadmin
  secret-key: minioadmin123
  project-bucket: projects